CREATE TABLE "Shapes" (
    "ShapeID" decimal(18,9) PRIMARY KEY,
    "Shape" varchar(255),
    "Description" varchar(1024),
    "DimensionTabIndex" decimal(18,9),
    "PriceFormat" varchar(50),
    "PriceFormatDisplay" varchar(255),
    "WeightFormat" varchar(50),
    "SurfaceAreaFormat" varchar(50),
    "PropertyFormat" varchar(50),
    "MaterialGroupID" decimal(18,9),
    "StandardClip" varchar(50),
    "Combining" varchar(50),
    "PDCPieceMarkRequired" varchar(50),
    "ShowShape" varchar(50),
    "ERPDesignation" varchar(255),
    "ExcludeFromInstanceTracking" varchar(50),
    "AllowSplit" varchar(50),
    "CostCodeID" decimal(18,9),
    "CostTypeID" decimal(18,9)
);

CREATE TABLE "Sizes" (
    "SizeID" decimal(25,12) PRIMARY KEY,
    "ShapeID" decimal(25,12),
    "DimDepth" decimal(25,12),
    "DimDepthImperial" decimal(25,12),
    "DimWidth" decimal(25,12),
    "DimWidthImperial" decimal(25,12),
    "DimWeight" decimal(25,12),
    "DimWeightImperial" decimal(25,12),
	"DimWeightMetric" decimal(25,12),
    "DimThickness" decimal(25,12),
    "DimThicknessImperial" decimal(25,12),
    "DimGage" varchar(255),
	"DimGageImperial" varchar(255),
    "DimDiameter" decimal(18,9),
	"DimDiameterImperial" decimal(18,9),
    "DimComment" varchar(1024),
    "SizeUnits" varchar(50),
    "BaseWeight" decimal(25,12),
    "UnitWeight" decimal(25,12),
    "XSectionalArea" decimal(25,12),
    "Depth" decimal(25,12),
    "FlangeWidth" decimal(25,12),
    "FlangeThickness" decimal(25,12),
    "WebThickness" decimal(25,12),
    "KDistance" decimal(25,12),
    "AdjustedK" decimal(25,12),
    "UsualGage" varchar(255),
    "SecondaryGage" varchar(255),
    "AxisXXS" decimal(25,12),
    "InsideDiameter" decimal(25,12),
    "OutsideDiameter" decimal(25,12),
    "WallThickness" decimal(25,12),
    "CalcRevaluation" varchar(50),
    "RevaluationLength1" decimal(25,12),
    "RevaluationLength2" decimal(25,12),
    "RevaluationLength3" decimal(25,12),
    "RevaluationPrice1" decimal(25,12),
    "RevaluationPrice2" decimal(25,12),
    "RevaluationPrice3" decimal(25,12),
    "ChargeLength" decimal(25,12),
    "CalcScrap" varchar(50),
    "ScrapWidth" decimal(25,12),
    "ScrapLength" decimal(25,12),
    "ScrapPrice" decimal(25,12),
    "Kerf" decimal(25,12),
    "KerfRipCut" decimal(25,12),
    "KerfCrossCut" decimal(25,12),
    "KerfInternalCut" decimal(25,12),
    "TrimLeadingWidth" decimal(25,12),
    "TrimLeadingLength" decimal(25,12),
    "TrimTrailingWidth" decimal(25,12),
    "TrimTrailingLength" decimal(25,12),
    "ClampAllowanceFromPart" decimal(25,12),
    "ValidCombiningScrapPercentage" decimal(25,12),
    "FirstCutCost" decimal(25,12),
    "FirstCutCharge" decimal(25,12),
    "AdditionalCutCost" decimal(25,12),
    "AdditionalCutCharge" decimal(25,12),
    "DimensionSizesImperial" varchar(255),
    "DimensionSizesImperial_Reverse" varchar(255),
    "DimensionSizesImperial_EDI" varchar(255),
    "Dim1Imperial"  varchar(255),
    "Dim1SortValue" varchar(255),
    "Dim2Imperial"  varchar(255),
    "Dim2SortValue" varchar(255),
    "Dim3Imperial"  varchar(255),
    "Dim3SortValue" varchar(255),
    "Dim4Imperial"  varchar(255),
    "Dim4SortValue" varchar(255),
    "Dim5Imperial"  varchar(255),
    "Dim5SortValue" varchar(255),
    "Dim6Imperial"  varchar(255),
    "Dim6SortValue" varchar(255),
    "SortOrder" decimal(25,12),
    "SortOrder_Reverse" decimal(25,12),
    "ProNestDesignation" varchar(255),
    "SigmaNestDesignation" varchar(255),
    "ERPDesignation" varchar(255),
    CONSTRAINT "fk_Sizes_ShapeID" FOREIGN KEY("ShapeID") REFERENCES "Shapes"("ShapeID")
);

CREATE TABLE "Grades" (
    "GradeID" decimal(18,9) PRIMARY KEY,
    "ShapeID" decimal(18,9),
    "Grade" varchar(255),
    "DefaultGrade" varchar(50),
    "WeightMultiplier" decimal(10,2),
    "ProNestDesignation" varchar(255),
    CONSTRAINT "fk_Grades_ShapeID" FOREIGN KEY("ShapeID") REFERENCES "Shapes"("ShapeID")
);

CREATE TABLE "LaborRates" (
    "LaborRateID" decimal(18,9) PRIMARY KEY,
    "Description" varchar(1024),
    "LaborRateCurrencyID" decimal(18,9),
    "LaborRate" decimal(10,2),
    "SpecialMeaning" varchar(255),
    "CostCodeID" decimal(18,9),
    "CostTypeID" decimal(18,9)
);

CREATE TABLE "LaborGroups" (
    "LaborGroupID" decimal(18,9) PRIMARY KEY,
    "Number" decimal(18,9),
    "Description" varchar(1024),
    "LaborRateID" decimal(18,9),
    "Activity" varchar(255),
    CONSTRAINT "fk_LaborGroups_LaborRateID" FOREIGN KEY("LaborRateID") REFERENCES "LaborRates"("LaborRateID")
);

CREATE TABLE "Estimates" (
    "EstimateID" decimal(18,9) PRIMARY KEY,
    "Estimator" varchar(255),
    "BidDate" date,
    "JobNumber" varchar(255),
    "JobName" varchar(255),
    "Location" varchar(255),
    "JobStatusID" decimal(18,9),
	"Other1" varchar(255),
	"Other2" varchar(255),
    "DistanceToJob" decimal(10,2),
    "ShopDrawingCostCurrencyID" decimal(18,9),
    "ShopDrawingCost" decimal(10,2),
	"ShopDrawingHours" decimal(10,2),
	"ShopEfficiency" decimal(10,2),
	"ShopSetupID" decimal(10,2),
	"AnglePricingTypeID" decimal(10,2),
	"BeamPricingTypeID" decimal(10,2),
	"PlatePricingTypeID" decimal(10,2),
	"RodPricingTypeID" decimal(10,2),
	"TubePricingTypeID" decimal(10,2),
	"OtherMaterialPricingTypeID" decimal(10,2),
	"PricingCombinationRunID" decimal(10,2),
	"LaborArchiveDateTime" date,
    "LaborArchiveID" decimal(18,9),
	"HistoricPricingDateTime" date,
	"CleaningTypeID" decimal(10,2),	
    "GalvanizingCostPerKilogramCurrencyID" decimal(18,9),
    "GalvanizingCostPerKilogram" decimal(10,2),
    "GalvanizingMinimumCostCurrencyID" decimal(18,9),
    "GalvanizingMinimumCost" decimal(10,2),
    "GalvanizingTruckWeight" decimal(10,2),
    "GalvanizingFreightCostCurrencyID" decimal(18,9),
    "GalvanizingFreightCost" decimal(10,2),
    "GalvanizingLaborCostCurrencyID" decimal(18,9),
    "GalvanizingLaborCost" decimal(10,2),
    "GalvanizingWeightPercent" decimal(5,2),
    "LengthInputTypeIDImperial" decimal(18,9),
    "ThicknessInputTypeIDImperial" decimal(18,9),
    "DefaultFinish" varchar(255),
    "DefaultPaintSystemID" decimal(18,9),
    "DefaultCleanSystemID" decimal(18,9),
    "ItemIncrement" decimal(18,9),
    "InputDisplayUnitsSize" varchar(50),
    "InputDisplayUnitsLength" varchar(50),
    "InputDisplayUnitsWeight" varchar(50),
    "InputDisplayUnitsPrice" varchar(50),
    "AutoClipAngles" varchar(50),
    "UseGradeSubstitutions" varchar(50),
    "ApplyKerfMult" varchar(50),
    "ApplyKerfNest" varchar(50),
    "CombiningRotatePlates" varchar(50),
    "CombiningAllowSplitTees" varchar(50),
    "NestingShearCut" varchar(50),
	"GroupName" varchar(50),
	"GroupName2" varchar(50),
	"ClientFirmID" decimal(18,9),
	"ClientShipToFirmAddressID" varchar(50),
	"ClientBillToFirmAddressID" varchar(50),
	"ClientFirmContactID" decimal(18,9),
	"ProjectID" decimal(18,9),
	"ExternalProjectID" decimal(18,9),
	"ERPJobNumber" decimal(18,9),
	"NumberOfItems" decimal(18,9),
	"TotalQuantity" decimal(18,9),
	"TotalLength" decimal(25,15),
	"TotalWeight" decimal(25,15),
	"TotalSurfaceArea" decimal(25,15),
	"TotalManHours" decimal(25,15),
	"UpdateCount" decimal(18,9),
	"ProductionCodeUpdateCount" decimal(18,9),
	"Recalculate" decimal(18,9),
	"RecalculateProductionCodeSummary" decimal(18,9),
	"RecalculateEstimateSummary" decimal(18,9),
	"EstimateSummaryUpdateCount" decimal(18,9)
);

CREATE TABLE "EstimateItems" (
    "EstimateItemID" decimal(18,9) PRIMARY KEY,
    "EstimateID" decimal(18,9),
    "ItemID" decimal(18,9),
    "Page" varchar(255),
    "AccessoryItemID" decimal(18,9),
    "PartNumber" varchar(255),
    "DimensionString" varchar(255),
    "DimensionStringMetric" varchar(255),
    "ManHours" decimal(25,15),
    "CalculatedManHours" decimal(25,15),
    "ManualOverrideSum" decimal(10,2),
    "CalculatedHash" varchar(255),
    "Weight" decimal(25,15),
    "WeightItem" decimal(25,15),
    "WeightWeld" decimal(25,15),
    "SurfaceArea" decimal(25,15),
    "Perimeter"decimal(25,15),
    "MaterialCostPricingTypeID" decimal(25,15),
    "MaterialCostCurrencyID" decimal(25,15),
    "MaterialUnitCost" decimal(25,15),
    "MaterialCost" decimal(25,15),
    "MaterialDropCost" decimal(25,15),
    "MaterialDropWeight" decimal(25,15),
    "MaterialCostUnits" decimal(25,15),
    "MaterialCostDate" date,
    "ShopBolts" decimal(25,15),
    "FieldBolts" decimal(25,15),
    "Quantity" decimal(25,15),
    "ShapeID" decimal(25,15),
    "SizeID" decimal(25,15),
    "DimDepth" decimal(25,15),
    "DimWidth" decimal(25,15),
    "DimWeight" decimal(25,15),
    "DimThickness" decimal(25,15),
    "DimGage" decimal(25,15),
    "DimDiameter" decimal(25,15),
    "DimComment" varchar(1024),
    "Length" decimal(25,15),
    "GradeID" decimal(25,15),
    "Camber" decimal(25,15),
    "EstimateExtraString" varchar(1024),
    "LaborCodeID" decimal(25,15),
    "Copes" decimal(25,15),
    "Holes" decimal(25,15),
    "HolesWithoutBolts" decimal(25,15),
    "Stiffeners" decimal(25,15),
    "TopFlangeHoles" decimal(25,15),
    "WebHoles" decimal(25,15),
    "BottomFlangeHoles" decimal(25,15),
    "WeldedStuds" decimal(25,15),
    "ManHoursPerPiece" decimal(25,15),
    "CostPerPieceCurrencyID" decimal(25,15),
    "CostPerPiece" decimal(25,15),
    "ManualUnitCostCurrencyID" decimal(25,15),
    "ManualUnitCost" decimal(25,15),
    "ManualCost" decimal(25,15),
    "ManualEstimateCostUnitID" decimal(25,15),
    "Finish" varchar(255),
    "PaintSystemID" decimal(25,15),
    "CleanSystemID" decimal(25,15),
    "CategoryID" decimal(25,15),
    "SubCategoryID" decimal(25,15),
    "Sequence" decimal(25,15),
    "MainPiece" decimal(25,15),
    "DetailingHours" decimal(25,15),
    "DetailingCostCurrencyID" decimal(25,15),
    "DetailingCost" decimal(25,15),
    "ErectHours" decimal(25,15),
    "ErectCostCurrencyID" decimal(25,15),
    "ErectCost" decimal(25,15),
    "Comment" varchar(1024),
    "ProductionCodeID" decimal(25,15),
    "EstimateStatusID" decimal(25,15),
    "CostCodeID" decimal(25,15),
    "CostTypeID" decimal(25,15),
    "Recalculate" decimal(25,15),
    "ReloadStandardClips" decimal(25,15),
    CONSTRAINT "fk_EstimateItems_EstimateID" FOREIGN KEY("EstimateID") REFERENCES "Estimates"("EstimateID"),
    CONSTRAINT "fk_EstimateItems_ShapeID" FOREIGN KEY("ShapeID") REFERENCES "Shapes"("ShapeID"),
    CONSTRAINT "fk_EstimateItems_SizeID" FOREIGN KEY("SizeID") REFERENCES "Sizes"("SizeID"),
    CONSTRAINT "fk_EstimateItems_GradeID" FOREIGN KEY("GradeID") REFERENCES "Grades"("GradeID")
);

CREATE TABLE "EstimateItemLabor" (
    "EstimateItemID" decimal(10,2),
    "LaborGroupID" decimal(10,2),
    "ManHours" decimal(10,2),
    "CalculatedManHours" decimal(10,2),
    CONSTRAINT "fk_EstimateItemLabor_EstimateItemID" FOREIGN KEY("EstimateItemID") REFERENCES "EstimateItems"("EstimateItemID"),
    CONSTRAINT "fk_EstimateItemLabor_LaborGroupID" FOREIGN KEY("LaborGroupID") REFERENCES "LaborGroups"("LaborGroupID")
);

SELECT * FROM "Grades"
